version: '3'
services:
    elk:
        image: sebp/elk
        container_name: elk
        ports:
        - "5601:5601" #kibana
        - "9200:9200" #elastic
        - "5044:5044" #logstash beats filebeat

    haproxy:
      image: haproxy:latest
      container_name: haproxy
      build:
        context: ./haproxy/
      ports:
        - "80:80"
        - "14567:14567"
        - "1936:1936"

    metricbeat:
      build:
        context: ./metricbeat
        args:
          - METRICBEAT_FILE=metricbeat.yml
          - ELK_HOST=$ELK_HOST
          - STAT_IP=$STAT_IP
      container_name: metricbeat
      depends_on:
        - haproxy
        - elk
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - WAIT_FOR_HOSTS='${ELK_HOST}:9200 ${ELK_HOST}:5601'
        - HOST_ELASTICSEARCH=$ELK_HOST:9200
        - HOST_KIBANA=$ELK_HOST:5601 

