version: '3'
services:
    elk:
        image: sebp/elk
        ports:
        - "5601:5601" #kibana
        - "9200:9200" #elastic
        - "5044:5044" #logstash beats filebeat

    haproxy:
      image: haproxy:latest
      build:
        context: ./haproxy/
      ports:
        - "80:80"
