metricbeat.modules:
- module: haproxy
  metricsets: ["stat"]
  period: 10s
  hosts: ["http://STAT_IP/stats"]
  enabled: true

output.elasticsearch:
  hosts: ["ELK_HOST:9200"]

setup.kibana:
  host: "ELK_HOST:5601"

setup.dashboards.enabled: true

logging.level: debug
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/metricbeat
  name: metricbeat.log
  keepfiles: 2
  permissions: 0644
