version: '3'

services:
  proxy:
    image: dockercloud/haproxy
    environment:
      - BALANCE=roundrobin
      - EXTRA_GLOBAL_SETTINGS=debug
      - EXTRA_FRONTEND_SETTINGS_FILE_8080=haproxy_frontend.cfg
      - ADDITIONAL_BACKEND_FILE_NODES=haproxy_backend.cfg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 80
    ports:
      - 80:80
